import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Template from './template'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Home - Next.js',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <Template>{children}</Template>
      </body>
    </html>
  )
}
