
import { Metadata } from 'next'
import { CounterComponent } from '@/app/components/Dashboard/Counter'

export const metadata: Metadata = {
  title: 'Counter - Dashboard',
  description: 'Counter generated by create next app',
}

const CounterPage = () => {
  return (
    <div className='flex flex-col items-center justify-center w-full h-full'>
      <span>Productos en el carrito</span>
      <CounterComponent />
    </div>
  )
}

export default CounterPage